osx_image: xcode11.6
language: objective-c
script:
- xcodebuild clean test -enableCodeCoverage YES -workspace Example/Ranger.Swift.ApiClientV1.xcworkspace -scheme Ranger.Swift.ApiClientV1-Example -destination 'platform=iOS Simulator,OS=13.6,name=iPhone 11' ONLY_ACTIVE_ARCH=NO | xcpretty
- pod lib lint
deploy:
  provider: script
  script: ./travis/trunk-push.sh
  on:
    tags: true